services:
#    ld_user.example:
#        class: Ld\UserBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    ld_user.registration.form.type:
        class: Ld\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%, '@service_container']
        tags:
            - { name: form.type, alias: ld_user_registration }
