<?php

namespace Ld\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
	public function getCustomerGridList($limit = 0, $offset = 10, $orderBy = "id", $sortOrder = "asc", $searchData, $SearchType, $objHelper,$admin) {
	
		$data = $this->trim_serach_data($searchData, $SearchType);
	
		$query = $this->createQueryBuilder('u')		            
                		->where('u.locked = :locked')
                		->setParameter('locked', 0)
                		->andWhere('u.isDeleted = :deleted')
                		->setParameter('deleted', 0)
                		->andWhere('u.roles LIKE :role')
                		->setParameter('role', '%ROLE_USER%');
	
		if ($SearchType == 'ORLIKE') {
	
			$likeStr = $objHelper->orLikeSearch($data);
		}
		if ($SearchType == 'ANDLIKE') {
	
			$likeStr = $objHelper->andLikeSearch($data);
		}
	
		if ($likeStr) {
	
			$query->andWhere($likeStr);
		}
	
		$query->orderBy($orderBy, $sortOrder);
		 
		$countData = count($query->getQuery()->getArrayResult());
		 
		$query->setMaxResults($limit);
		$query->setFirstResult($offset);
		 
		$result = $query->getQuery()->getResult();
	
		$dataResult = array();
		 
		if ($countData > 0) {
	
			$dataResult['result'] 		= $result;
			$dataResult['totalRecord'] 	= $countData;
			 
			return $dataResult;
		}
		return false;
	}
	
	public function getAdminGridList($limit = 0, $offset = 10, $orderBy = "id", $sortOrder = "asc", $searchData, $SearchType, $objHelper,$admin) {
	
		$data = $this->trim_serach_data($searchData, $SearchType);
	
		$query = $this->createQueryBuilder('u')		            
                		->where('u.locked = :locked')
                		->setParameter('locked', 0)
                		->andWhere('u.isDeleted = :deleted')
                		->setParameter('deleted', 0)
                		->andWhere('u.roles LIKE :role')
                		->setParameter('role', '%ROLE_ADMIN%');
	
		if ($SearchType == 'ORLIKE') {
	
			$likeStr = $objHelper->orLikeSearch($data);
		}
		if ($SearchType == 'ANDLIKE') {
	
			$likeStr = $objHelper->andLikeSearch($data);
		}
	
		if ($likeStr) {
	
			$query->andWhere($likeStr);
		}
	
		$query->orderBy($orderBy, $sortOrder);
			
		$countData = count($query->getQuery()->getArrayResult());
			
		$query->setMaxResults($limit);
		$query->setFirstResult($offset);
			
		$result = $query->getQuery()->getResult();
	
		$dataResult = array();
			
		if ($countData > 0) {
	
			$dataResult['result'] 		= $result;
			$dataResult['totalRecord'] 	= $countData;
	
			return $dataResult;
		}
		return false;
	}
	
	public function trim_serach_data($searchData, $SearchType) {
	
		$QueryStr = array();
	
		if (!empty($searchData)) {
	
			if ($SearchType == 'ANDLIKE') {
	
				$i = 0;
				foreach ($searchData as $key => $val) {
	
					if ($key == 'firstname' && !empty($val)) {
					
						$QueryStr[$i]['Field'] = 'u.firstname';
						$QueryStr[$i]['Value'] = $val;
						$QueryStr[$i]['Operator'] = 'LIKE';
					}
					
					if ($key == 'lastname' && !empty($val)) {
							
						$QueryStr[$i]['Field'] = 'u.lastname';
						$QueryStr[$i]['Value'] = $val;
						$QueryStr[$i]['Operator'] = 'LIKE';
					}
					
					if ($key == 'username' && !empty($val)) {
	
						$QueryStr[$i]['Field'] = 'u.username';
						$QueryStr[$i]['Value'] = $val;
						$QueryStr[$i]['Operator'] = 'LIKE';
					}
	
					if ($key == 'email' && !empty($val)) {
	
						$QueryStr[$i]['Field'] = 'u.email';
						$QueryStr[$i]['Value'] = $val ;
						$QueryStr[$i]['Operator'] = 'LIKE';
					}
	
					$i++;
				}
			} else {
	
			}
		}
		return $QueryStr;
	}
}
